# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: '22.10.0'
    hooks:
      - id: black
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 'v2.0.0'
      hooks:
      - id: flake8
  -   repo: https://github.com/PyCQA/isort
      rev: '5.10.1'  # Use the sha / tag you want to point at
      hooks:
      -   id: isort
  - repo: local
    hooks:    
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: ''
        entry: mypy
        language: python
        'types_or': [python, pyi]
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: '2.9.2'
